/*
 * This file was automatically generated by EvoSuite
 * Mon Jul 18 15:32:54 GMT 2016
 */

package org.objectweb.cjdbc.common.exceptions.driver.protocol;

import org.junit.Test;
import static xcorpus.AssertionAdapter.*;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.objectweb.cjdbc.common.exceptions.driver.protocol.ControllerCoreException;
import org.objectweb.cjdbc.common.stream.CJDBCInputStream;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class ControllerCoreException_ESTest extends ControllerCoreException_ESTest_scaffolding {

  //Test case number: 0
  /*
   * 1 covered goal:
   * Goal 1. org.objectweb.cjdbc.common.exceptions.driver.protocol.ControllerCoreException.<init>(Ljava/lang/Throwable;)V: root-Branch
   */

	@Test(timeout=300000)
  public void test0()  throws Throwable  {
      ControllerCoreException controllerCoreException0 = null;
      try {
        controllerCoreException0 = new ControllerCoreException((Throwable) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("org.objectweb.cjdbc.common.exceptions.driver.protocol.SerializableException", e);
      }
  }

  //Test case number: 1
  /*
   * 1 covered goal:
   * Goal 1. org.objectweb.cjdbc.common.exceptions.driver.protocol.ControllerCoreException.<init>(Lorg/objectweb/cjdbc/common/stream/CJDBCInputStream;)V: root-Branch
   */

	@Test(timeout=300000)
  public void test1()  throws Throwable  {
      ControllerCoreException controllerCoreException0 = null;
      try {
        controllerCoreException0 = new ControllerCoreException((CJDBCInputStream) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("org.objectweb.cjdbc.common.exceptions.driver.protocol.SerializableException", e);
      }
  }
}
