/*
 * This file was automatically generated by EvoSuite
 * Mon Jul 18 15:44:22 GMT 2016
 */

package org.objectweb.cjdbc.common.exceptions;

import org.junit.Test;
import static xcorpus.AssertionAdapter.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.objectweb.cjdbc.common.exceptions.ControllerException;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class ControllerException_ESTest extends ControllerException_ESTest_scaffolding {

  //Test case number: 0
  /*
   * 1 covered goal:
   * Goal 1. org.objectweb.cjdbc.common.exceptions.ControllerException.<init>(Ljava/lang/String;)V: root-Branch
   */

	@Test(timeout=300000)
  public void test0()  throws Throwable  {
      ControllerException controllerException0 = new ControllerException("org.objectweb.cjdbc.common.exceptions.ControllerException");
  }

  //Test case number: 1
  /*
   * 2 covered goals:
   * Goal 1. org.objectweb.cjdbc.common.exceptions.ControllerException.<init>(Ljava/lang/String;Ljava/lang/Throwable;)V: root-Branch
   * Goal 2. org.objectweb.cjdbc.common.exceptions.ControllerException.<init>()V: root-Branch
   */

	@Test(timeout=300000)
  public void test1()  throws Throwable  {
      ControllerException controllerException0 = new ControllerException();
      ControllerException controllerException1 = new ControllerException("org.objectweb.cjdbc.common.exceptions.ControllerException", (Throwable) controllerException0);
      assertFalse(controllerException1.equals((Object)controllerException0));
  }

  //Test case number: 2
  /*
   * 2 covered goals:
   * Goal 1. org.objectweb.cjdbc.common.exceptions.ControllerException.<init>(Ljava/lang/Throwable;)V: root-Branch
   * Goal 2. org.objectweb.cjdbc.common.exceptions.ControllerException.<init>()V: root-Branch
   */

	@Test(timeout=300000)
  public void test2()  throws Throwable  {
      ControllerException controllerException0 = new ControllerException();
      ControllerException controllerException1 = new ControllerException((Throwable) controllerException0);
      assertFalse(controllerException1.equals((Object)controllerException0));
  }
}
